<a href="https://colab.research.google.com/github/riyasharma1202/AIML/blob/main/experiment_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
a=np.array([3,7,0,12,56,34,87,12,88,12,9])
a

array([ 3,  7,  0, 12, 56, 34, 87, 12, 88, 12,  9])

In [3]:
b=np.array([1,2,3, 1.684, 5.375, 7.234,6, 77.44, 5, 9, 12])
b

array([ 1.   ,  2.   ,  3.   ,  1.684,  5.375,  7.234,  6.   , 77.44 ,
        5.   ,  9.   , 12.   ])

In [4]:
c=(a+b)
c

array([ 4.   ,  9.   ,  3.   , 13.684, 61.375, 41.234, 93.   , 89.44 ,
       93.   , 21.   , 21.   ])

In [5]:
d= np.array([(1,2,3,4),(5,6,7,8)])
d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
e= np.array([(1,2,3,4),(5,6,7,8)], dtype=float)
e

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [7]:
f=d+e
f

array([[ 2.,  4.,  6.,  8.],
       [10., 12., 14., 16.]])

In [8]:
c.sort()
c

array([ 3.   ,  4.   ,  9.   , 13.684, 21.   , 21.   , 41.234, 61.375,
       89.44 , 93.   , 93.   ])

In [9]:
g=np.zeros((3,4))
g

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
g=np.ones((2,3,4),dtype=np.int16)
g

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [11]:
d=np.arange(10,25,5)
d

array([10, 15, 20])

In [12]:
m=np.linspace(0,2,9)
m

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [13]:
e=np.full((2,2),7)
e

array([[7, 7],
       [7, 7]])

In [14]:
f=np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

In [15]:
u=np.random.random((2,2))
u

array([[2.27901537e-01, 5.69465783e-02],
       [6.66379197e-04, 9.94728707e-01]])

In [16]:
y=np.empty((3,2))
y

array([[4.76175825e-310, 0.00000000e+000],
       [2.26178760e-080, 8.74179370e+189],
       [4.19332841e+228, 1.70887473e+214]])